# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dipak
tagline:          ''
description:      'MS CS at USC'
url:              http://dipakwani.com
baseurl:          'http://dipakwani.com'

author:
  name:           'Dipak Wani'

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/wandip
