# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dipak
tagline:          ''
description:      'Curious'
url:              http://dipakwani.com
baseurl:          '/'

author:
  name:           'Dipak Wani'

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate, jekyll-feed]

google-analytics: UA-127095421-1
github:
  repo:           https://github.com/wandip
